### ISSUE TITLE
建议数据库的初始化脚本，通过配置可以在程序启动时执行。

### ISSUE THREAD

**Issue by crazyStar00** [YunaiV/ruoyi-vue-pro#123]
之前看shenyu[https://github.com/apache/incubator-shenyu](url)的shenyu-admin模块是这样做的。
```
shenyu:
  database:
    dialect: h2
    init_script: "sql-script/h2/schema.sql"
    init_enable: true
```
LocalDataSourceLoader类中完成sql的执行，通过org.apache.ibatis.jdbc.ScriptRunner

我觉得这样的好处，在于用户不用去手动导入sql脚本了。但是坏处呢，就是如果初始化参数忘记修改，导致sql脚本执行多次，可能会出现问题。
