### ISSUE TITLE
当指定数据库自增生成策略 id-type 为 ASSIGN_ID 时，系统写入错误日志时异常 infra_api_error_log

### ISSUE THREAD

**Issue by chopperkuang** [YunaiV/ruoyi-vue-pro#634]
### 基本信息

- ruoyi-vue-pro 版本：2.2.0-jdk8-snapshot
- 操作系统：macos
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：
infra_api_error_log 和  infra_config 表的 id 为 int，应该是 bigint 

### 复现步骤

第一步，
```
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
```

第二步，

第三步，

### 报错信息
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/b443adef-5389-4b25-a741-9751ad77f24e">
